-- The 30 classes the ResNet50 pipeline is already trained on.
-- Marked status='trained' so the similarity system knows what the CNN covers.
insert into taxonomy (plant, disease, status, source) values
  ('Apple Tree','Mosaic Disease','trained','trained'),
  ('Apple Tree','Rust','trained','trained'),
  ('Apple Tree','Scab','trained','trained'),
  ('Apple Tree','Spider Mite','trained','trained'),
  ('Bell Pepper','Leaf Spot','trained','trained'),
  ('Cassava','Brown Leaf Spot','trained','trained'),
  ('Cassava','Mosaic','trained','trained'),
  ('Cassava','Root Rot','trained','trained'),
  ('Chinese Cabbage','Downy Mildew','trained','trained'),
  ('Chinese Rose','Gray Mold','trained','trained'),
  ('Chinese Rose','Powdery Mildew','trained','trained'),
  ('Citrus Tree','Citrus Leaf Miner','trained','trained'),
  ('Corn-Maize','Leaf Disease','trained','trained'),
  ('Corn-Maize','Rust','trained','trained'),
  ('Corn-Maize','Streak','trained','trained'),
  ('Corn-Maize','Stripe','trained','trained'),
  ('Corn-Maize','Yellowing','trained','trained'),
  ('Grape','Black Rot','trained','trained'),
  ('Mango Tree','Anthracnose','trained','trained'),
  ('Pea','Downy Mildew','trained','trained'),
  ('Peach Tree','Shot Hole Disease','trained','trained'),
  ('Pear Tree','Blister Mites','trained','trained'),
  ('Pear Tree','Powdery Mildew','trained','trained'),
  ('Pear Tree','Rust','trained','trained'),
  ('Potato','Blight','trained','trained'),
  ('Squash','Powdery Mildew','trained','trained'),
  ('Tomato','Blight','trained','trained'),
  ('Tomato','Leaf Mold','trained','trained'),
  ('Tomato','Viral Disease','trained','trained'),
  ('Wheat','Tan Spot','trained','trained')
on conflict (plant, disease) do nothing;
